if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "MENUHELP input does not exist: ${INPUT}")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "MENUHELP output path was not provided")
endif()

file(STRINGS "${INPUT}" menuhelp_lines)
set(menuhelp_entries "")
set(menuhelp_count 0)
foreach(line IN LISTS menuhelp_lines)
    if(line MATCHES "^[^,]*,[ \t]*(\".*\")[ \t]*$")
        string(APPEND menuhelp_entries "    ${CMAKE_MATCH_1},\n")
        math(EXPR menuhelp_count "${menuhelp_count} + 1")
    endif()
endforeach()
if(menuhelp_count EQUAL 0)
    message(FATAL_ERROR "No menu-help strings found in: ${INPUT}")
endif()

set(menuhelp_header "/* Generated from MENUHELP.TXT. Do not edit. */\n")
string(APPEND menuhelp_header "#ifdef OPUS_X64\n")
string(APPEND menuhelp_header "CODE char * const opus_x64_menu_help_strings[] =\n{\n")
string(APPEND menuhelp_header "${menuhelp_entries}")
string(APPEND menuhelp_header "};\n")
string(APPEND menuhelp_header "#define OPUS_X64_MENU_HELP_STRING(iidstr) \\\n    (opus_x64_menu_help_strings[(iidstr)])\n")
string(APPEND menuhelp_header "#endif /* OPUS_X64 */\n")
file(WRITE "${OUTPUT}" "${menuhelp_header}")
